## Recitation 1

In [1]:
import numpy as np
import scipy.linalg as la

from sympy import Matrix

### Problem 1

In [2]:
a = np.array([2, -1, 0, 0, 0, 0, 0, 0, 0, 0])
K10 = la.toeplitz(a)
K10

array([[ 2, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  2, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  2, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  2, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  2, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  2, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  2, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  2, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  2, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  2]])

In [3]:
np.linalg.inv(K10) * 11

array([[10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 9., 18., 16., 14., 12., 10.,  8.,  6.,  4.,  2.],
       [ 8., 16., 24., 21., 18., 15., 12.,  9.,  6.,  3.],
       [ 7., 14., 21., 28., 24., 20., 16., 12.,  8.,  4.],
       [ 6., 12., 18., 24., 30., 25., 20., 15., 10.,  5.],
       [ 5., 10., 15., 20., 25., 30., 24., 18., 12.,  6.],
       [ 4.,  8., 12., 16., 20., 24., 28., 21., 14.,  7.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 16.,  8.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

### Problem 5

In [4]:
a = np.array([2, -1, 0, -1])
f4 = np.array([1, -1, 1, -1]).T
C4 = la.toeplitz(a)
C4

array([[ 2, -1,  0, -1],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [-1,  0, -1,  2]])

In [5]:
np.linalg.solve(C4, f4)

array([0.5, 0. , 0.5, 0. ])

In [6]:
np.matmul(np.linalg.pinv(C4), f4)

array([ 0.25, -0.25,  0.25, -0.25])

In [7]:
np.linalg.lstsq(C4, f4, rcond=None)[0]

array([ 0.25, -0.25,  0.25, -0.25])

### Problem 10

In [8]:
a = np.array([2, -1, 0, 0, 0, 0, 0, 0, 0, 0])
T10 = la.toeplitz(a)
T10[0, 0] = 1
T10

array([[ 1, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  2, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  2, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  2, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  2, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  2, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  2, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  2, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  2, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  2]])

In [9]:
np.linalg.inv(T10)

array([[10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 9.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 8.,  8.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 7.,  7.,  7.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 6.,  6.,  6.,  6.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  4.,  3.,  2.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  3.,  2.,  1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  2.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### Problem 14

In [10]:
a = np.array([2, -1, 0, 0])
B4 = la.toeplitz(a)
B4[0, 0] = 1
B4[3, 3] = 1
B4

array([[ 1, -1,  0,  0],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [ 0,  0, -1,  1]])

In [11]:
np.linalg.eig(B4)

EigResult(eigenvalues=array([3.41421356e+00, 2.00000000e+00, 6.21107307e-17, 5.85786438e-01]), eigenvectors=array([[ 0.27059805,  0.5       , -0.5       , -0.65328148],
       [-0.65328148, -0.5       , -0.5       , -0.27059805],
       [ 0.65328148, -0.5       , -0.5       ,  0.27059805],
       [-0.27059805,  0.5       , -0.5       ,  0.65328148]]))

In [12]:
Matrix(B4).eigenvals()

{2: 1, 2 - sqrt(2): 1, sqrt(2) + 2: 1, 0: 1}

### Problem 20

In [13]:
def isToeplitz(A):
    m, n = A.shape
    # If symmetric
    if m != n or A.T.all() != A.all():
        return False
    # If Toeplitz
    for k in range(m - 1):
        for i in range(m - 2):
            j = -i + k
            if A[i][j] != A[i + 1][j + 1]:
                return False
    return True